apiVersion: v1
kind: Secret
metadata:
  name: "compras-app-secret-{{ .Values.env }}"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db_user: {{ .Values.postgresql.auth.username | b64enc | quote }}
  db_password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  db_name: {{ .Values.postgresql.auth.database | b64enc | quote }}
  jwt_secret: {{ .Values.comprasweb.jwtSecret | b64enc | quote }}
  google_client_id: {{ .Values.comprasweb.googleClientId | b64enc | quote }}
  google_client_secret: {{ .Values.comprasweb.googleClientSecret | b64enc | quote }}
